# Generated by Django 4.2.11 on 2024-12-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0002_alter_student_firstname_alter_student_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
